export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const SET_USERS = 'SET_USERS';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS';
export const GET_SESSION_ERROR = 'GET_SESSION_ERROR';

export const SET_USER = 'SET_USER';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_ERROR = 'SET_USER_ERROR';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const GET_RESPONSE = 'GET_RESPONSE';
export const GET_RESPONSE_SUCCESS = 'GET_RESPONSE_SUCCESS';
export const GET_RESPONSE_ERROR = 'GET_RESPONSE_ERROR';

export const GET_TRANSCRIPT = 'GET_TRANSCRIPT';
export const GET_TRANSCRIPT_SUCCESS = 'GET_TRANSCRIPT_SUCCESS';
export const GET_TRANSCRIPT_ERROR = 'GET_TRANSCRIPT_ERROR';

export const GET_RESPONSES = 'GET_RESPONSES';
export const GET_RESPONSES_SUCCESS = 'GET_RESPONSES_SUCCESS';
export const GET_RESPONSES_ERROR = 'GET_RESPONSE_ERROR';

export const SET_RESPONSE = 'SET_RESPONSE';
export const SET_RESPONSE_SUCCESS = 'SET_RESPONSE_SUCCESS';
export const SET_RESPONSE_ERROR = 'SET_RESPONSE_ERROR';

export const SET_RESPONSES = 'SET_RESPONSES';
export const SET_RESPONSES_SUCCESS = 'SET_RESPONSES_SUCCESS';
export const SET_RESPONSES_ERROR = 'SET_RESPONSES_ERROR';

export const GET_RUN = 'GET_RUN';
export const GET_RUN_SUCCESS = 'GET_RUN_SUCCESS';
export const GET_RUN_ERROR = 'GET_RUN_ERROR';

export const GET_RUNS = 'GET_RUNS';
export const GET_RUNS_SUCCESS = 'GET_RUNS_SUCCESS';
export const GET_RUNS_ERROR = 'GET_RUNS_ERROR';

export const GET_RUN_DATA = 'GET_RUN_DATA';
export const GET_RUN_DATA_SUCCESS = 'GET_RUN_DATA_SUCCESS';
export const GET_RUN_DATA_ERROR = 'GET_RUN_DATA_ERROR';

export const SET_USER_ROLE_SUCCESS = 'SET_USER_ROLE_SUCCESS';
export const SET_USER_ROLE_ERROR = 'SET_USER_ROLE_ERROR';

export const SET_RUN = 'SET_RUN';
export const SET_RUN_SUCCESS = 'SET_RUN_SUCCESS';
export const SET_RUN_ERROR = 'SET_RUN_ERROR';

export const DELETE_SCENARIO_SUCCESS = 'DELETE_SCENARIO_SUCCESS';
export const DELETE_SCENARIO_ERROR = 'DELETE_SCENARIO_ERROR';

export const UNLOCK_SCENARIO_SUCCESS = 'UNLOCK_SCENARIO_SUCCESS';
export const UNLOCK_SCENARIO_ERROR = 'UNLOCK_SCENARIO_ERROR';

export const GET_SCENARIO = 'GET_SCENARIO';
export const GET_SCENARIO_SUCCESS = 'GET_SCENARIO_SUCCESS';
export const GET_SCENARIO_ERROR = 'GET_SCENARIO_ERROR';

export const GET_SCENARIOS = 'GET_SCENARIOS';
export const GET_SCENARIOS_SUCCESS = 'GET_SCENARIOS_SUCCESS';
export const GET_SCENARIOS_ERROR = 'GET_SCENARIOS_ERROR';

export const SET_SCENARIO = 'SET_SCENARIO';
export const SET_SCENARIO_SUCCESS = 'SET_SCENARIO_SUCCESS';
export const SET_SCENARIO_ERROR = 'SET_SCENARIO_ERROR';

export const GET_RUN_HISTORY = 'GET_RUN_HISTORY';
export const GET_RUN_HISTORY_SUCCESS = 'GET_RUN_HISTORY_SUCCESS';
export const GET_RUN_HISTORY_ERROR = 'GET_RUN_HISTORY_ERROR';

export const SET_SCENARIOS = 'SET_SCENARIOS';
export const SET_SCENARIOS_SUCCESS = 'SET_SCENARIOS_SUCCESS';
export const SET_SCENARIOS_ERROR = 'SET_SCENARIOS_ERROR';

export const DELETE_SLIDE_SUCCESS = 'DELETE_SLIDE_SUCCESS';
export const DELETE_SLIDE_ERROR = 'DELETE_SLIDE_ERROR';

export const SET_SLIDES = 'SET_SLIDES';

export const GET_SLIDES = 'GET_SLIDES';
export const GET_SLIDES_SUCCESS = 'GET_SLIDES_SUCCESS';
export const GET_SLIDES_ERROR = 'GET_SLIDES_ERROR';

export const CREATE_COHORT = 'CREATE_COHORT';
export const CREATE_COHORT_SUCCESS = 'CREATE_COHORT_SUCCESS';
export const CREATE_COHORT_ERROR = 'CREATE_COHORT_ERROR';

export const SET_COHORT = 'SET_COHORT';
export const SET_COHORT_SUCCESS = 'SET_COHORT_SUCCESS';
export const SET_COHORT_ERROR = 'SET_COHORT_ERROR';

export const SET_COHORT_USER_ROLE = 'SET_COHORT_USER_ROLE';
export const SET_COHORT_USER_ROLE_SUCCESS = 'SET_COHORT_USER_ROLE_SUCCESS';
export const SET_COHORT_USER_ROLE_ERROR = 'SET_COHORT_USER_ROLE_ERROR';

export const GET_COHORT = 'GET_COHORT';
export const GET_COHORT_SUCCESS = 'GET_COHORT_SUCCESS';
export const GET_COHORT_ERROR = 'GET_COHORT_ERROR';

export const GET_COHORT_DATA = 'GET_COHORT_DATA';
export const GET_COHORT_RUN_DATA_SUCCESS = 'GET_COHORT_RUN_DATA_SUCCESS';
export const GET_COHORT_RUN_DATA_ERROR = 'GET_COHORT_RUN_DATA_ERROR';

export const GET_COHORT_PARTICIPANTS = 'GET_COHORT_PARTICIPANTS';
export const GET_COHORT_PARTICIPANTS_SUCCESS =
  'GET_COHORT_PARTICIPANTS_SUCCESS';
export const GET_COHORT_PARTICIPANTS_ERROR = 'GET_COHORT_PARTICIPANTS_ERROR';

export const LINK_RUN_TO_COHORT = 'LINK_RUN_TO_COHORT';
export const LINK_RUN_TO_COHORT_SUCCESS = 'LINK_RUN_TO_COHORT_SUCCESS';
export const LINK_RUN_TO_COHORT_ERROR = 'LINK_RUN_TO_COHORT_ERROR';

export const GET_ALL_COHORTS = 'GET_ALL_COHORTS';
export const GET_ALL_COHORTS_SUCCESS = 'GET_ALL_COHORTS_SUCCESS';
export const GET_ALL_COHORTS_ERROR = 'GET_ALL_COHORTS_ERROR';

export const GET_USER_COHORTS = 'GET_USER_COHORTS';
export const GET_USER_COHORTS_SUCCESS = 'GET_USER_COHORTS_SUCCESS';
export const GET_USER_COHORTS_ERROR = 'GET_USER_COHORTS_ERROR';
