export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const SET_RUN = 'SET_RUN';

export const SET_USERS = 'SET_USERS';

export const GET_SCENARIO = 'GET_SCENARIO';
export const GET_SCENARIO_SUCCESS = 'GET_SCENARIO_SUCCESS';
export const GET_SCENARIO_ERROR = 'GET_SCENARIO_ERROR';

export const GET_SCENARIOS = 'GET_SCENARIOS';
export const GET_SCENARIOS_SUCCESS = 'GET_SCENARIOS_SUCCESS';
export const GET_SCENARIOS_ERROR = 'GET_SCENARIOS_ERROR';

export const SET_SCENARIO = 'SET_SCENARIO';
export const SET_SCENARIO_SUCCESS = 'SET_SCENARIO_SUCCESS';
export const SET_SCENARIO_ERROR = 'SET_SCENARIO_ERROR';

export const SET_SCENARIOS = 'SET_SCENARIOS';
export const SET_SCENARIOS_SUCCESS = 'SET_SCENARIOS_SUCCESS';
export const SET_SCENARIOS_ERROR = 'SET_SCENARIOS_ERROR';

export const SET_SLIDES = 'SET_SLIDES';

export const COHORT_REQUEST_LIST = 'COHORT_REQUEST_LIST';
export const COHORT_REQUEST_LIST_SUCCESS = 'COHORT_REQUEST_LIST_SUCCESS';
export const COHORT_REQUEST_LIST_ERROR = 'COHORT_REQUEST_LIST_ERROR';

export const COHORT_CREATE = 'COHORT_CREATE';
export const COHORT_CREATE_SUCCESS = 'COHORT_CREATE_SUCCESS';
export const COHORT_CREATE_ERROR = 'COHORT_CREATE_ERROR';
